/* eslint-disable */
import React, { useState } from 'react'

const ANTHROPIC_MODEL = "claude-sonnet-4-20250514"

const AUDIT_DIMENSIONS = [
  { key: "website",     label: "Website",             icon: "🌐" },
  { key: "booking",     label: "Online Booking",       icon: "📅" },
  { key: "automations", label: "Automations",          icon: "⚙️" },
  { key: "whatsapp",    label: "WhatsApp Automation",  icon: "💬" },
  { key: "reviews",     label: "Review Automation",    icon: "⭐" },
  { key: "seo",         label: "SEO",                  icon: "🔍" },
  { key: "localSeo",    label: "Local SEO",            icon: "📍" },
]

const STATUS_CONFIG = {
  good:    { label: "Good",        color: "#00e5a0", bg: "rgba(0,229,160,0.1)",   dot: "#00e5a0" },
  weak:    { label: "Needs Work",  color: "#f5a623", bg: "rgba(245,166,35,0.1)",  dot: "#f5a623" },
  missing: { label: "Missing",     color: "#ff4d6d", bg: "rgba(255,77,109,0.1)",  dot: "#ff4d6d" },
}

async function callClaude(messages, systemPrompt) {
  const apiKey = process.env.REACT_APP_ANTHROPIC_KEY
  if (!apiKey) throw new Error("API key not configured. Add REACT_APP_ANTHROPIC_KEY in Vercel environment variables.")
  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
      "anthropic-dangerous-direct-browser-access": "true",
    },
    body: JSON.stringify({
      model: ANTHROPIC_MODEL,
      max_tokens: 1000,
      system: systemPrompt,
      messages,
      tools: [{ type: "web_search_20250305", name: "web_search" }],
    }),
  })
  const data = await response.json()
  if (!response.ok) throw new Error(data.error?.message || "API error")
  return data
}

function extractText(data) {
  return data.content.filter(b => b.type === "text").map(b => b.text).join("\n")
}

function parseJSON(text) {
  const clean = text.replace(/```json|```/g, "").trim()
  const match = clean.match(/\{[\s\S]*\}/)
  if (match) return JSON.parse(match[0])
  throw new Error("No JSON found")
}

function exportPDF(business, auditData) {
  const win = window.open("", "_blank")
  const statusEmoji = { good: "✅", weak: "⚠️", missing: "❌" }
  const rows = AUDIT_DIMENSIONS.map(dim => {
    const d = auditData[dim.key] || {}
    return `<tr>
      <td style="padding:12px 16px;border-bottom:1px solid #e5e7eb;font-weight:600">${dim.icon} ${dim.label}</td>
      <td style="padding:12px 16px;border-bottom:1px solid #e5e7eb">${statusEmoji[d.status] || "—"} ${STATUS_CONFIG[d.status]?.label || "—"}</td>
      <td style="padding:12px 16px;border-bottom:1px solid #e5e7eb">${d.finding || "—"}</td>
      <td style="padding:12px 16px;border-bottom:1px solid #e5e7eb;color:#7c3aed;font-style:italic">${d.pitch || "—"}</td>
    </tr>`
  }).join("")
  win.document.write(`<html><head><title>Business Audit — ${business.name}</title>
    <style>body{font-family:Georgia,serif;color:#111;margin:40px}table{width:100%;border-collapse:collapse}th{background:#111;color:#fff;padding:12px 16px;text-align:left}</style>
    </head><body>
    <h1 style="margin-bottom:4px">Business Audit Report</h1>
    <h2 style="color:#7c3aed;margin-top:0">${business.name}</h2>
    <p style="color:#555">${business.address} &nbsp;|&nbsp; ${business.phone}</p>
    <p style="color:#555">Generated: ${new Date().toLocaleDateString("en-IN",{day:"numeric",month:"long",year:"numeric"})}</p>
    <hr style="margin:24px 0">
    <table><thead><tr><th>Dimension</th><th>Status</th><th>Finding</th><th>Pitch Hook</th></tr></thead>
    <tbody>${rows}</tbody></table>
    <p style="margin-top:32px;font-size:12px;color:#999">Generated by AgastyaOne Business Audit Scanner</p>
    </body></html>`)
  win.document.close()
  setTimeout(() => win.print(), 500)
}

function AuditCard({ dim, data }) {
  const cfg = STATUS_CONFIG[data?.status] || STATUS_CONFIG.missing
  return (
    <div style={{ background:"var(--bg2)", border:"1px solid var(--border)", borderRadius:"var(--radius)", padding:"18px 20px", display:"flex", flexDirection:"column", gap:10 }}>
      <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center" }}>
        <span style={{ fontSize:14, fontWeight:700, color:"var(--text)" }}>{dim.icon} {dim.label}</span>
        <span style={{ fontSize:11, fontWeight:700, letterSpacing:1, textTransform:"uppercase", color:cfg.color, background:cfg.bg, padding:"3px 10px", borderRadius:20 }}>
          {cfg.label}
        </span>
      </div>
      <p style={{ margin:0, fontSize:13, color:"var(--text2)", lineHeight:1.6 }}>{data?.finding || "—"}</p>
      {data?.pitch && (
        <div style={{ borderLeft:`3px solid ${cfg.color}`, paddingLeft:12, fontSize:12, color:"var(--accent2)", fontStyle:"italic", lineHeight:1.5 }}>
          💡 {data.pitch}
        </div>
      )}
    </div>
  )
}

function ScoreBadge({ score }) {
  const color = score >= 70 ? "#00e5a0" : score >= 40 ? "#f5a623" : "#ff4d6d"
  return (
    <div style={{ width:80, height:80, borderRadius:"50%", border:`4px solid ${color}`, display:"flex", flexDirection:"column", alignItems:"center", justifyContent:"center", flexShrink:0 }}>
      <span style={{ fontSize:24, fontWeight:800, color, fontFamily:"var(--font-display)" }}>{score}</span>
      <span style={{ fontSize:9, color:"var(--text3)", letterSpacing:1 }}>/ 100</span>
    </div>
  )
}

export default function AuditPage() {
  const [query, setQuery] = useState("")
  const [city, setCity] = useState("")
  const [stage, setStage] = useState("search")
  const [businesses, setBusinesses] = useState([])
  const [selected, setSelected] = useState(null)
  const [auditData, setAuditData] = useState(null)
  const [score, setScore] = useState(null)
  const [loading, setLoading] = useState(false)
  const [loadingMsg, setLoadingMsg] = useState("")
  const [error, setError] = useState("")

  async function searchBusinesses() {
    if (!query.trim()) return
    setLoading(true); setError(""); setStage("search")
    setLoadingMsg("Searching the web for matching businesses...")
    try {
      const data = await callClaude(
        [{ role:"user", content:`Find businesses matching: "${query}" in "${city || "India"}". Return top 5 results.` }],
        `You are a business finder. Search the web for businesses matching the user query. Return ONLY a JSON object like:
{"businesses":[{"name":"","address":"","phone":"","website":"","category":""}]}
No markdown, no extra text. Return up to 5 businesses with real details.`
      )
      const text = extractText(data)
      const parsed = parseJSON(text)
      setBusinesses(parsed.businesses || [])
      setStage("results")
    } catch (e) {
      setError(e.message.includes("API key") ? "⚠️ API key not configured — add REACT_APP_ANTHROPIC_KEY in Vercel settings." : "Search failed. Please try again.")
    } finally {
      setLoading(false)
    }
  }

  async function runAudit(biz) {
    setSelected(biz); setStage("auditing"); setError("")
    const steps = [
      "Checking website presence...",
      "Analysing booking systems...",
      "Scanning automation signals...",
      "Looking for WhatsApp Business...",
      "Reviewing Google ratings & reviews...",
      "Auditing SEO signals...",
      "Checking local SEO & Google Maps...",
      "Generating pitch insights...",
    ]
    let si = 0
    setLoadingMsg(steps[0])
    const interval = setInterval(() => { si++; if (si < steps.length) setLoadingMsg(steps[si]) }, 3500)
    try {
      const data = await callClaude(
        [{ role:"user", content:`Run a full digital presence audit for: ${biz.name}, ${biz.address}. Website: ${biz.website || "unknown"}. Phone: ${biz.phone || "unknown"}.` }],
        `You are a digital audit expert for AgastyaOne, a Bengaluru-based digital agency. Audit the business across 7 dimensions and return ONLY a JSON object:
{
  "score": <0-100 integer>,
  "website":     {"status":"good|weak|missing","finding":"<1-2 sentences>","pitch":"<sales hook for AgastyaOne>"},
  "booking":     {"status":"good|weak|missing","finding":"...","pitch":"..."},
  "automations": {"status":"good|weak|missing","finding":"...","pitch":"..."},
  "whatsapp":    {"status":"good|weak|missing","finding":"...","pitch":"..."},
  "reviews":     {"status":"good|weak|missing","finding":"...","pitch":"..."},
  "seo":         {"status":"good|weak|missing","finding":"...","pitch":"..."},
  "localSeo":    {"status":"good|weak|missing","finding":"...","pitch":"..."}
}
Search the web for real information. Be specific and honest. Pitch hooks should be compelling one-liners that AgastyaOne can use in a sales call. No markdown, no extra text.`
      )
      clearInterval(interval)
      const text = extractText(data)
      const parsed = parseJSON(text)
      setAuditData(parsed)
      setScore(parsed.score || 0)
      setStage("audit")
    } catch (e) {
      clearInterval(interval)
      setError("Audit failed. Please try again.")
      setStage("results")
    }
  }

  return (
    <div>
      {/* Header */}
      <div style={{ marginBottom:24 }}>
        <div style={{ fontFamily:"var(--font-display)", fontSize:20, fontWeight:800, marginBottom:4 }}>
          ⚡ Business Audit Scanner
        </div>
        <div style={{ fontSize:13, color:"var(--text3)" }}>
          Search any local business → select → get a full digital audit with sales insights
        </div>
      </div>

      {/* Search Box */}
      <div className="card" style={{ marginBottom:20 }}>
        <div style={{ display:"flex", gap:10, flexWrap:"wrap" }}>
          <input
            value={query}
            onChange={e => setQuery(e.target.value)}
            onKeyDown={e => e.key === "Enter" && searchBusinesses()}
            placeholder="Business name e.g. Centric Dental Care"
            className="form-input"
            style={{ flex:2, minWidth:200 }}
          />
          <input
            value={city}
            onChange={e => setCity(e.target.value)}
            onKeyDown={e => e.key === "Enter" && searchBusinesses()}
            placeholder="City (optional)"
            className="form-input"
            style={{ flex:1, minWidth:120 }}
          />
          <button
            onClick={searchBusinesses}
            disabled={loading || !query.trim()}
            className="btn btn-primary"
            style={{ whiteSpace:"nowrap" }}
          >
            {loading && stage === "search" ? "Searching..." : "🔍 Search"}
          </button>
        </div>
      </div>

      {error && (
        <div style={{ background:"var(--red-bg)", border:"1px solid rgba(248,113,113,0.3)", borderRadius:"var(--radius-sm)", padding:14, marginBottom:20, color:"var(--red)", fontSize:13 }}>
          {error}
        </div>
      )}

      {/* Loading */}
      {(loading || stage === "auditing") && (
        <div style={{ textAlign:"center", padding:"40px 20px" }}>
          <div className="spinner" style={{ width:40, height:40, borderWidth:3, margin:"0 auto 20px" }} />
          <p style={{ color:"var(--accent2)", fontSize:14, fontWeight:600 }}>{loadingMsg}</p>
        </div>
      )}

      {/* Results */}
      {stage === "results" && !loading && businesses.length > 0 && (
        <div>
          <div style={{ fontSize:11, color:"var(--text3)", letterSpacing:1, textTransform:"uppercase", marginBottom:12, fontWeight:700 }}>
            Select a business to audit
          </div>
          <div style={{ display:"flex", flexDirection:"column", gap:10 }}>
            {businesses.map((biz, i) => (
              <div key={i} onClick={() => runAudit(biz)}
                style={{ background:"var(--bg2)", border:"1px solid var(--border)", borderRadius:"var(--radius)", padding:"16px 20px", cursor:"pointer", display:"flex", justifyContent:"space-between", alignItems:"center", transition:"border-color 0.2s", boxShadow:"var(--shadow)" }}
                onMouseEnter={e => e.currentTarget.style.borderColor="var(--accent)"}
                onMouseLeave={e => e.currentTarget.style.borderColor="var(--border)"}
              >
                <div>
                  <div style={{ fontWeight:700, fontSize:14, marginBottom:4 }}>{biz.name}</div>
                  <div style={{ fontSize:12, color:"var(--text3)" }}>{biz.address}</div>
                  {biz.phone && <div style={{ fontSize:12, color:"var(--text3)" }}>{biz.phone}</div>}
                  {biz.website && <div style={{ fontSize:11, color:"var(--accent2)", marginTop:2 }}>{biz.website}</div>}
                </div>
                <span style={{ fontSize:18, color:"var(--accent)" }}>→</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {stage === "results" && !loading && businesses.length === 0 && (
        <div className="empty-state"><p>No businesses found</p><span>Try a different search term</span></div>
      )}

      {/* Audit Report */}
      {stage === "audit" && auditData && selected && (
        <div>
          {/* Business header */}
          <div className="card" style={{ marginBottom:16, display:"flex", justifyContent:"space-between", alignItems:"center", flexWrap:"wrap", gap:16 }}>
            <div>
              <div style={{ fontSize:11, color:"var(--accent2)", letterSpacing:1, textTransform:"uppercase", marginBottom:4, fontWeight:700 }}>Audit Report</div>
              <div style={{ fontWeight:800, fontSize:20, fontFamily:"var(--font-display)" }}>{selected.name}</div>
              <div style={{ fontSize:12, color:"var(--text3)", marginTop:4 }}>{selected.address} · {selected.phone}</div>
            </div>
            <ScoreBadge score={score} />
          </div>

          {/* Audit grid */}
          <div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))", gap:12, marginBottom:16 }}>
            {AUDIT_DIMENSIONS.map(dim => (
              <AuditCard key={dim.key} dim={dim} data={auditData[dim.key]} />
            ))}
          </div>

          {/* Actions */}
          <div style={{ display:"flex", gap:10, flexWrap:"wrap" }}>
            <button onClick={() => exportPDF(selected, auditData)} className="btn btn-primary">
              📄 Download PDF Report
            </button>
            <button onClick={() => { setStage("results"); setAuditData(null) }} className="btn btn-ghost">
              ← Back to Results
            </button>
            <button onClick={() => { setStage("search"); setBusinesses([]); setQuery(""); setCity(""); setAuditData(null) }} className="btn btn-ghost">
              🔍 New Search
            </button>
          </div>
        </div>
      )}
    </div>
  )
}
